### ISSUE TITLE
unsupported option '-fopenmp' on Mac OS X

### ISSUE THREAD

**Issue by rakshitkr** [glciampaglia/knowledge_linker#10]
I'm getting the below output while trying to run setup.py file on MacOS Mojave

$ python setup.py nosetests
running nosetests
running egg_info
writing requirements to knowledge_linker.egg-info/requires.txt
writing knowledge_linker.egg-info/PKG-INFO
writing top-level names to knowledge_linker.egg-info/top_level.txt
writing dependency_links to knowledge_linker.egg-info/dependency_links.txt
writing entry points to knowledge_linker.egg-info/entry_points.txt
reading manifest file 'knowledge_linker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'LICENSE.txt'
writing manifest file 'knowledge_linker.egg-info/SOURCES.txt'
building 'knowledge_linker.algorithms._maxmin' extension
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/Library/Python/2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c knowledge_linker/algorithms/_maxmin.c -o build/temp.macosx-10.14-intel-2.7/knowledge_linker/algorithms/_maxmin.o -fopenmp
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
error: command 'cc' failed with exit status 1

**Comment by glciampaglia** [comment]
Hi, the code depends on OpenMP to parallelize some tasks, so you should have the OpenMP header files and other dependencies installed on your system.

Unfortunately I don't know what is the best way to set up the right developer environment on MacOS these days, but if you Google a bit you should find it. Perhaps a full installation of Anaconda Python could provide you with all the necessary headers.

Also, I should point out that the code has been tested only with gcc, while you are using Clang. I cannot provide help with issues arising from different compilers; on the other hand if you do manage to get Clang to work please let me know. 

Closing for now; feel free to open again if needed.
