### ISSUE TITLE
2 Failures & 1 Error occurring while running "python setup.py nosetests"

### ISSUE THREAD

**Issue by rakshitkr** [glciampaglia/knowledge_linker#11]
I'm getting the following error & failures while trying to run the test cases

----------------------------------------------------------------------
ERROR: Test 'backbone' metric againt NetworkX (Rion's testing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/knowledge_linker/knowledge_linker/tests/test_closure.py", line 422, in test_backbone_metric
    DG.add_edge(n1, n2, {'weight_sum':sum_path_weights})
TypeError: add_edge() takes exactly 3 arguments (4 given)

---------------------------------------------------------------------
FAIL: Doctest: knowledge_linker.algorithms.closure.closuress
---------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for knowledge_linker.algorithms.closure.closuress
  File "/knowledge_linker/knowledge_linker/algorithms/closure.py", line 114, in closuress

----------------------------------------------------------------------
FAIL: closure on E-R random graph.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/knowledge_linker/knowledge_linker/tests/test_closure.py", line 95, in test_closure_rand
    assert np.all(p1 == p2)
AssertionError

----------------------------------------------------------------------

REPORT FILE:
https://openload.co/f/dCKlFZq9X6g/docker_kl_report1.txt

**Comment by glciampaglia** [comment]
Mmmh, one of the errors is happening in one of the tests by @rionbr. Looks like newer versions of NetworkX have changed the signature of `add_edge`. Can you try to run it again with an older version of NetworkX, like 1.11? To install a version other than the latest with pip you should do:
```
pip install -U networkx==1.10
```

**Comment by rakshitkr** [comment]
After downgrading networkx package to 1.10 I was only able to get rid of error. But the two failures still seems to persist.

**Comment by glciampaglia** [comment]
The first one is just about how floating point numbers on your platforms are displayed. Numerically the results are correct.

The second one is a known issue. In short, the Cython implementation sometimes returns a different path from the pure Python one; see issue #1 for more information. Unfortunately I haven't had the time ever since I found it to look into it. Unless you need the actual paths, but just the value of the proximity score, then you should be fine. 

Closing the issue now; feel free to reopen if there are other problems. Thanks!
