### ISSUE TITLE
Using importnt to create WKG

### ISSUE THREAD

**Issue by apogre** [glciampaglia/knowledge_linker#5]
`importnt allns.tsv instance_types_en.nt `

WARNING: the n-triples file must be already sorted by source, destination!

Traceback (most recent call last):
  File "/home/kenv/bin/importnt", line 11, in <module>
    load_entry_point('knowledge-linker==0.1rc0', 'console_scripts', 'importnt')()
  File "build/bdist.linux-x86_64/egg/knowledge_linker/io/importnt.py", line 127, in main
NameError: global name 'readns' is not defined

**Comment by glciampaglia** [comment]
Hi, this should have been fixed. Please pull again and let us know if it does not work. Closing for now. Thanks for your patience. Big thanks to @shiralkarprashant for the help!
