### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by tcrosenk** [glciampaglia/knowledge_linker#7]
Hello,

I am very interested in this project. I have installed and used ontoparse & importnt to create the adjacency matrices. 

I am interested in the confmatrix command of klinker but I am a bit confused on what each of the options mean.

  uris                     node uris
  graph                 adjacency matrix
  source               sources input file
  target                 targets input file
  output                output file

I know that graph would the adjacency graph, but the other I would love some extra details. Thank you!

**Comment by glciampaglia** [comment]
Hi, thanks for your interesting in Knowledge Linker!

The `confmatrix` command takes in input a list of N sources and a list of N targets, where each source is associated to exactly one target (for example Presidents of the US and First Ladies of the US) and computes the NxN matrix of all proximity scores between any (source, target) pair. The items on the diagonal are the true matching pairs, and the ones off the diagonal are "incorrect" pairs. When computing the score for a diagonal entry, it additionally removes any direct link it finds, i.e., it performs link prediction. The output is a NxN matrix of scores. To get an idea, you may look at Fig. 3 of the [related paper on PLOS ONE](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0128193).

The arguments are the following:

* `uris` list of URIs of all nodes, in the same order as they appear in the adjacency matrix. It is one of the output files produced by `importnt`.
* `sources` CSV file with two columns -- numeric node ID and URI of each source
* `targets` CSV file with two columns -- numeric node ID and URI of each target
* `output` path to the file where to write the output matrix

Hope that helps! Closing for now but feel free to reopen if you have additional questions.
